name: nham_nham
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  flutter_svg: ^2.2.3
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/datasources/mocks/
    - assets/category/
    - assets/discount_card/
    - assets/restaurants/
    - assets/restaurants/restaurants_cover/
    - assets/restaurants/restaurants_icon/
    - assets/foods/
    - assets/feature/